---



version: 2



build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
  commands:
    - PYTHON=python3 make -s venv-create
    - PYTHON=python3 make -s sphinx
    - mkdir _readthedocs
    - mv docs/html _readthedocs



python:
  install:
    - requirements: reqs-develop.txt
    - method: pip
      path: .
      extra_requirements:
        - all



sphinx:
  configuration: docs/conf.py
