---



name: Validate



# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches:
      - main



jobs:


  validate310:
    name: Python 3.10
    runs-on: ubuntu-latest
    env:
      PYTHON: python3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Makefile
        run: |
          make -s venv-create
          make -s check


  validate311:
    name: Python 3.11
    runs-on: ubuntu-latest
    env:
      PYTHON: python3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Makefile
        run: |
          make -s venv-create
          make -s check

      - name: Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true
