---



name: Validate



# yamllint disable-line rule:truthy
on:

  schedule:
    - cron: '0 2 * * *'

  pull_request:

  push:
    branches:
      - main



jobs:


  validate311:
    name: Python 3.11
    runs-on: ubuntu-latest
    env:
      PYTHON: python3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Makefile
        run: |
          make -s venv-create
          make -s check


  validate312:
    name: Python 3.12
    runs-on: ubuntu-latest
    env:
      PYTHON: python3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Makefile
        run: |
          make -s venv-create
          make -s check

      - name: Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true
